<a href="https://colab.research.google.com/github/iesous-kurios/famprom/blob/master/Final_Breeze_push_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
giving = pd.read_excel('/content/fpspokane-giving-01-05-2021 (1).xlsx')

In [3]:
people = pd.read_excel('/content/fpspokane-people-01-05-2021.xlsx')

In [4]:
giving.head()

         Date  Batch  ...  Card                                               Note
0  2021-01-04    229  ...   NaN                                                NaN
1  2021-01-03    229  ...   NaN                                                NaN
2  2021-01-03    229  ...   NaN  Night Without a Bed Pledge -- one full year fo...
3  2021-01-02    228  ...   NaN                                                NaN
4  2021-01-02    228  ...   NaN                                                NaN

[5 rows x 13 columns]

In [8]:
giving = giving.rename(columns = {'Person ID': 'Breeze ID'})

In [9]:
giving.head()

         Date  Batch  ...  Card                                               Note
0  2021-01-04    229  ...   NaN                                                NaN
1  2021-01-03    229  ...   NaN                                                NaN
2  2021-01-03    229  ...   NaN  Night Without a Bed Pledge -- one full year fo...
3  2021-01-02    228  ...   NaN                                                NaN
4  2021-01-02    228  ...   NaN                                                NaN

[5 rows x 13 columns]

In [5]:
people.head()

   Breeze ID First Name  ... Causes or Passion  Added Date
0   21464546        Pam  ...               NaN  01/23/2020
1   21463258       Emma  ...               NaN  01/23/2020
2   21463354       Geng  ...               NaN  01/23/2020
3   21463704       John  ...               NaN  01/23/2020
4   21464136      Lydia  ...               NaN  01/23/2020

[5 rows x 73 columns]

In [10]:
people_giving = giving.merge(people, on = 'Breeze ID')

In [11]:
people.shape

(6405, 73)

In [12]:
giving.shape

(7757, 13)

In [13]:
people_giving.shape

(7754, 85)

In [14]:
people_giving.head()

         Date  Batch  ...  Causes or Passion  Added Date
0  2021-01-04    229  ...                NaN  08/17/2020
1  2020-12-04    224  ...                NaN  08/17/2020
2  2020-11-04    219  ...                NaN  08/17/2020
3  2020-10-04    213  ...                NaN  08/17/2020
4  2020-09-04    202  ...                NaN  08/17/2020

[5 rows x 85 columns]

In [15]:
people_giving.to_excel('/content/people_giving.xlsx')